name: 01 - Hello World

on:
    workflow_dispatch:
    #push:
    #    branches: [main]
  
jobs:
    hello:
        runs-on: ubuntu-24.04
        steps:
            - name: saludar
              run: echo "Hello World!"

            - name: Ver fecha del runner
              run: date

            - name: Ver archivos disponibles
              run: ls -la

    repo-files:
        runs-on: ubuntu-24.04
        steps:
            - name: Descargar código del repositorio
              uses: actions/checkout@v6

            - name: Ver archivos disponibles en el repositorio
              run: ls -la              
              