name: 05 - CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]    

jobs:
    ci:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Preparar pnpm
              uses: pnpm/action-setup@v6
              with:
                    version: 11
                    run_install: false

            - name: Instalar dependencias
              run: |
                    cd 09-ci-cd
                    echo "::group::Instalar dependencias"
                    pnpm install --frozen-lockfile
                    echo "::endgroup::"

            - name: Lint
              run: |
                    cd 09-ci-cd
                    echo "::group::lint"
                    pnpm lint
                    echo "::endgroup::"

            - name: Test
              run: |
                    cd 09-ci-cd
                    echo "::group::Test"
                    pnpm test
                    echo "::endgroup::"

            - name: Build
              run: |
                    cd 09-ci-cd
                    echo "::group::Build"
                    pnpm build              
                    echo "::endgroup::"