name: 05 - CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]    

jobs:
    frontend-lint:
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v6         
          
        - name: Setup pnpm and Node.js
          uses: ./.github/actions/setup-pnpm-ci-cd     

        - name: Lint
          run: |
                cd 09-ci-cd
                echo "::group::lint"
                pnpm lint:frontend
                echo "::endgroup::"

    frontend-test:
      runs-on: ubuntu-24.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v6  

        - name: Setup pnpm and Node.js
          uses: ./.github/actions/setup-pnpm-ci-cd     

        - name: Test
          run: |
                cd 09-ci-cd
                echo "::group::test"
                pnpm test:frontend
                echo "::endgroup::"
                
    backend-lint:
      runs-on: ubuntu-24.04
      steps:
          - name: Checkout code
            uses: actions/checkout@v6  

          - name: Setup pnpm and Node.js
            uses: ./.github/actions/setup-pnpm-ci-cd     

          - name: Lint
            run: |
                  cd 09-ci-cd/backend
                  echo "::group::lint"
                  pnpm lint:backend
                  echo "::endgroup::"
                  
    backend-test:
      runs-on: ubuntu-24.04
      steps:
          - name: Checkout code
            uses: actions/checkout@v6          

          - name: Setup pnpm and Node.js
            uses: ./.github/actions/setup-pnpm-ci-cd           

          - name: Test
            run: |
                  cd 09-ci-cd/backend
                  echo "::group::test"
                  pnpm test:backend
                  echo "::endgroup::"                  